### PR TITLE
Suggestion on badigeon.javac/get-classpath

### PR DESCRIPTION
**Pull request by ajchemist**
let classpath calculation to be able to take :aliases into account

### CODE REVIEW

**Comment by EwenG** [comment]
Thanks for your contribution,
I think it would be better if get-classpath was part of the public API (maybe in its own namespace?). get-classpath could take keyword arguments and customizing the classpath used by the javac command coud be done using the javac command arguments (the -cp flag). This way things would be less coupled and get-classpath could be used to customize the classpath of other commands (such as badigeon.compile).
What do you think of it ?

**Comment by ajchemist** [comment]
Sounds good to me.
However I've been modifying this library to fit my needs, so I'll have to drop this request at this point
By the way thanks for your efforts.

**Comment by EwenG** [comment]
May I ask what is your use case?
I usually setup my projects such that building a project does not require using aliases. I keep aliases to add things during development/testing.
However I am curious about other workflows.

**Comment by ajchemist** [comment]
Simply, a dependency that is not included in an artifact may be needed at compile time.

 I modified the library to suit my use case all day. Feel free to take a look. https://github.com/EwenG/badigeon/compare/master...aJchemist:master

oh, and documentation are rarely added. sorry about that.

**Comment by EwenG** [comment]
Thanks, this looks fine.

**Pull request closed without merging**
